<a href="https://colab.research.google.com/github/chin0104/DPDM2023/blob/main/Frequent_Patterns_(Association_Rules).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/My Drive/DPDM2021_DATA'

Mounted at /content/drive

In [ ]:
data = pd.read_csv(os.path.join(path,'reduced_marketbasket.csv'),encoding='latin-1')

In [ ]:
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/09/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/09/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/09/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/09/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/09/2011 12:50,4.95,12680.0,France

In [ ]:
data[data['StockCode']== '22386']
JUMBO BAG PINK POLKADOT

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
86,536378,22386,JUMBO BAG PINK POLKADOT,10,12/01/2010 09:37,1.95,14688.0,United Kingdom
789,536464,22386,JUMBO BAG PINK POLKADOT,1,12/01/2010 12:23,1.95,17968.0,United Kingdom
1428,536542,22386,JUMBO BAG PINK POLKADOT,30,12/01/2010 14:11,1.95,16456.0,United Kingdom
2427,536591,22386,JUMBO BAG PINK POLKADOT,1,12/01/2010 16:57,1.95,14606.0,United Kingdom
2712,536592,22386,JUMBO BAG PINK POLKADOT,3,12/01/2010 17:06,4.21,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
534742,581167,22386,JUMBO BAG PINK POLKADOT,20,12/07/2011 14:52,2.08,13534.0,United Kingdom
537138,581238,22386,JUMBO BAG PINK POLKADOT,5,12/08/2011 10:53,4.13,NaN,United Kingdom
539585,581439,22386,JUMBO BAG PINK POLKADOT,2,12/08/2011 16:30,4.13,NaN,United Kingdom
541421,581498,22386,JUMBO BAG PINK POLKADOT,1,12/09/2011 10:26,4.13,NaN,United Kingdom
541806,581579,22386,JUMBO BAG PINK POLKADOT,10,12/09/2011 12:19,1.79,17581.0,United Kingdom

In [ ]:
data.groupby('StockCode').max()

<ipython-input-12-7f62bde03018>:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  data.groupby('StockCode').max()

,InvoiceNo,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
StockCode,,,,,,
10002,551429,180,4/28/2011 15:05,1.66,18079.0,United Kingdom
10080,577801,170,9/27/2011 9:24,0.85,18096.0,United Kingdom
10120,580502,30,9/28/2011 15:18,0.21,18043.0,United Kingdom
10123C,560213,3,7/15/2011 15:05,0.65,17967.0,United Kingdom
10123G,549349,-38,04/08/2011 11:13,0.00,NaN,United Kingdom
...,...,...,...,...,...,...
gift_0001_20,573585,10,6/24/2011 15:51,17.02,NaN,United Kingdom
gift_0001_30,565231,30,8/30/2011 10:48,25.53,NaN,United Kingdom
gift_0001_40,561513,1,7/27/2011 15:12,34.04,NaN,United Kingdom
gift_0001_50,558614,1,6/30/2011 15:56,42.55,NaN,United Kingdom
m,539736,1,12/21/2010 15:18,2.55,NaN,United Kingdom

In [ ]:
data.groupby('Country').count()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID
Country,,,,,,,
Australia,1259,1259,1259,1259,1259,1259,1259
Austria,401,401,401,401,401,401,401
Bahrain,19,19,19,19,19,19,17
Belgium,2069,2069,2069,2069,2069,2069,2069
Brazil,32,32,32,32,32,32,32
Canada,151,151,151,151,151,151,151
Channel Islands,758,758,758,758,758,758,758
Cyprus,622,622,622,622,622,622,622
Czech Republic,30,30,30,30,30,30,30
Denmark,389,389,389,389,389,389,389
EIRE,8196,8196,8196,8196,8196,8196,7485
European Community,61,61,61,61,61,61,61
Finland,695,695,695,695,695,695,695
France,8557,8557,8557,8557,8557,8557,8491
Germany,9495,9495,9495,9495,9495,9495,9495
Greece,146,146,146,146,146,146,146
Hong Kong,288,288,288,288,288,288,0
Iceland,182,182,182,182,182,182,182
Israel,297,297,297,297,297,297,250
Italy,803,803,803,803,803,803,803
Japan,358,358,358,358,358,358,358
Lebanon,45,45,45,45,45,45,45
Lithuania,35,35,35,35,35,35,35
Malta,127,127,127,127,127,127,127
Netherlands,2371,2371,2371,2371,2371,2371,2371
Norway,1086,1086,1086,1086,1086,1086,1086
Poland,341,341,341,341,341,341,341
Portugal,1519,1519,1519,1519,1519,1519,1480
RSA,58,58,58,58,58,58,58
Saudi Arabia,10,10,10,10,10,10,10
Singapore,229,229,229,229,229,229,229
Spain,2533,2533,2533,2533,2533,2533,2533
Sweden,462,462,462,462,462,462,462
Switzerland,2002,2002,2002,2002,2002,2002,1877
USA,291,291,291,291,291,291,291
United Arab Emirates,68,68,68,68,68,68,68
United Kingdom,495478,495478,494024,495478,495478,495478,361878
Unspecified,446,446,446,446,446,446,244

In [ ]:
data.groupby('InvoiceNo')['StockCode'].apply(list)

InvoiceNo
536365     [85123A, 71053, 84406B, 84029G, 84029E, 22752,...
536366                                        [22633, 22632]
536367     [84879, 22745, 22748, 22749, 22310, 84969, 226...
536368                          [22960, 22913, 22912, 22914]
536369                                               [21756]
                                 ...
C581484                                              [23843]
C581490                                       [22178, 23144]
C581499                                                  [M]
C581568                                              [21258]
C581569                                       [84978, 20979]
Name: StockCode, Length: 25900, dtype: object

In [ ]:
transactions = data.groupby('InvoiceNo')['StockCode'].apply(list)

ทำ Association Rules

In [ ]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5955 sha256=c067eedfb34d332bb886c208e2d01fe951bde34464813187a6f88ceb76056194
  Stored in directory: /root/.cache/pip/wheels/c4/1a/79/20f55c470a50bb3702a8cb7c94d8ada15573538c7f4baebe2d
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [ ]:
from apyori import apriori

In [ ]:
frequentItemsets = list(apriori(transactions,min_support = 0.065))
frequentItemsets

[RelationRecord(items=frozenset({'22423'}), support=0.08386100386100385, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'22423'}), confidence=0.08386100386100385, lift=1.0)]),
 RelationRecord(items=frozenset({'47566'}), support=0.06586872586872587, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'47566'}), confidence=0.06586872586872587, lift=1.0)]),
 RelationRecord(items=frozenset({'85099B'}), support=0.08243243243243244, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'85099B'}), confidence=0.08243243243243244, lift=1.0)]),
 RelationRecord(items=frozenset({'85123A'}), support=0.08671814671814672, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'85123A'}), confidence=0.08671814671814672, lift=1.0)])]

In [ ]:
len(frequentItemsets)

4

In [ ]:
frequentItemsets[0][0]

frozenset({'22423'})

In [ ]:
min_sup = 0.01

frequentItemsets = list(apriori(transactions,min_support = 0.065))
for i in frequentItemsets:
  if i[0]._len_() > 1:
    print('yes')
    print(i)

AttributeError: ignored